package dev.weft.android.persistence

import android.content.Context
import app.cash.sqldelight.driver.android.AndroidSqliteDriver
import com.osmerion.android.database.sqlite.OsmerionSQLiteOpenHelperFactory
import dev.weft.android.db.WeftDatabase

/**
 * Builds the singleton SQLDelight [WeftDatabase] used by every
 * persistent store the substrate ships: MemoryStore, ScriptStorage,
 * ScheduledNotificationStore, TraceStore, UsageStore, ConversationStore.
 *
 * One database file (`substrate.db`) per app, in the app's internal
 * storage. The schema lives in the `.sq` files under
 * `src/main/sqldelight/dev/weft/android/db/`; migration workflow + rules
 * live in `MIGRATIONS.md` in that same directory.
 *
 * **Bundled SQLite**: we open the DB through Osmerion's `sqlite-android`
 * (a maintained fork of requery/sqlite-android) which ships a modern
 * SQLite compiled with FTS5 and every other feature we use. The default
 * `FrameworkSQLiteOpenHelperFactory` would route through Android's
 * framework SQLite, whose feature set varies by device — notably, FTS5
 * isn't reliably present below API 27, and some vendor builds strip it
 * even higher. The bundled driver removes that uncertainty entirely.
 *
 * Versioning: SQLDelight derives the schema version from
 * `1 + count(*.sqm files)`. [AndroidSqliteDriver] passes the schema to
 * SQLiteOpenHelper, which calls `Schema.create()` on first install and
 * `Schema.migrate(driver, from, to)` on subsequent upgrades — both
 * generated by SQLDelight from the `.sq` + `.sqm` files. No manual
 * migration plumbing needed.
 *
 * App authors don't normally call this directly — [WeftRuntime]
 * builds the database once and threads it into each store.
 */
public object WeftDatabaseFactory {
    /** Default DB filename. Apps wanting a different name pass their own. */
    public const val DEFAULT_DB_NAME: String = "substrate.db"

    public fun create(context: Context, name: String = DEFAULT_DB_NAME): WeftDatabase {
        val driver = AndroidSqliteDriver(
            schema = WeftDatabase.Schema,
            context = context.applicationContext,
            name = name,
            factory = OsmerionSQLiteOpenHelperFactory(),
        )
        return WeftDatabase(driver)
    }
}
