package dev.weft.harness.behavior

import kotlinx.serialization.Serializable

/**
 * Configuration for `harness-behavior` — the substrate's prompt-composition,
 * compaction, and (in the future) prompt-caching policy. Wired into
 * WeftAgent at construction; applied per turn.
 *
 * Mirrors the design in `docs/07-harness.md` "harness-behavior".
 */
data class BehaviorConfig(
    /**
     * If true (default), the device snapshot (time/timezone/locale) is prepended
     * to the latest user message instead of being mixed into the system prompt.
     * This keeps the system layer cacheable when caching is enabled.
     */
    val deviceSnapshotInUserMessage: Boolean = true,

    // --- Compaction ---
    val compactionStrategy: CompactionStrategy = CompactionStrategy.SlidingWindow(keepLastN = 20),

    /** Trigger compaction once history reaches this many user/assistant turns. */
    val compactionTriggerTurns: Int = 30,

    /** Estimated input-token threshold. Rough heuristic until we plug a real tokenizer. */
    val compactionTriggerInputTokens: Int = 50_000,

    // --- Prompt caching ---
    /**
     * Cache configuration. Koog 0.8.0 does NOT yet wire Anthropic-specific
     * cache_control markers — these settings are read but no cache_control
     * is emitted to Anthropic until Koog adds support (or we fork). Bedrock
     * cache markers ARE wired and could be used if/when we add a Bedrock
     * provider. See `docs/follow-ups.md`.
     */
    val cacheEnabled: Boolean = false,
    val cacheSystemAndTools: Boolean = true,
    val cacheHistory: Boolean = true,
    val cacheMinTokens: Int = 1024,
    val cacheTtl: CacheTtl = CacheTtl.FiveMinutes,
)

@Serializable
enum class CacheTtl { FiveMinutes, OneHour }

/**
 * How to reduce a long conversation history before sending it to the LLM.
 *
 * Trade-offs:
 *  - [None] — keep everything. Cheapest to implement, most expensive in tokens.
 *  - [DropOldest] — drop the oldest user/assistant pair when over threshold.
 *    Recent context is preserved; early context is lost completely.
 *  - [SlidingWindow] — always keep only the last N turns. Predictable cost,
 *    but truncation can be abrupt.
 *  - [Summarize] — replace dropped turns with a short summary message
 *    generated by [recapModelId]. Best context-preservation but slow + costs
 *    an extra LLM call. Not implemented in v1.
 */
@Serializable
sealed class CompactionStrategy {
    @Serializable data object None : CompactionStrategy()
    @Serializable data object DropOldest : CompactionStrategy()
    @Serializable data class SlidingWindow(val keepLastN: Int) : CompactionStrategy()
    @Serializable data class Summarize(val recapModelId: String) : CompactionStrategy()
}
